backend:
  name: git-gateway
  branch: master  # O "main" si tu rama es main
  identity_url: "https://earnest-brigadeiros-86fdd1.netlify.app/.netlify/identity"

media_folder: "images/uploads"  # Carpeta donde se guardan imágenes en GitHub
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"  # Carpeta donde se guardarán las páginas editadas
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }

