backend:
  name: test-repo  # Esto deshabilita la autenticaci칩n temporalmente

media_folder: "images/uploads"  # Carpeta donde se guardan im치genes en GitHub
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"  # Carpeta donde se guardar치n las p치ginas editadas
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }


